# Generated by Django 3.1.2 on 2020-10-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='users',
            name='drink',
            field=models.CharField(default='water', max_length=9),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='victor', max_length=30),
        ),
    ]
